#!/usr/bin/env bash
# To use this make sure the above line points to your local bash and that this file is executable with chmod +x (http://stackoverflow.com/a/817098)
# Also make sure Django local development server is running
rm -rf ~/Sites/hth.dev && mkdir ~/Sites/hth.dev && cd ~/Sites/hth.dev && wget --mirror --no-host-directories --directory-prefix ~/Sites/hth.dev http://127.0.0.1:8000; rsync -exclude='.DS_Store' -cavzhe ssh ~/Sites/hth.dev/ hth@hth.webfactional.com:webapps/hth/; cd -
